config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'groups#index'

  resources :groups, only: [:new, :create, :edit, :update] do
    scope module: 'groups' do
      resources :messages, only: [:index, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages

  validates :name, uniqueness: true, presence: true

  before_validation :member_present_check

  private

  def member_present_check
    throw(:abort) unless self.user_ids.present?
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :group

  validates :comment, presence: true, unless: :image_present_check

  mount_uploader :image, MessageImageUploader

  private

  def image_present_check
    self.image.present?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages

  validates :name, presence: true, uniqueness: true

  scope :except_for, ->(user){ where.not(id: user).order(name: :desc) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups/messages_controller.rb
class Groups::MessagesController < ApplicationController

  def index
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = current_user.messages.new(message_params)

    if @message.save
      flash[:notice] = '送信成功'
    else
      flash[:alert] = @message.errors.full_messages.join("。")
    end

    redirect_to group_messages_path(params[:group_id])
  end

  private

  def message_params
    params.require(:message).permit(:comment, :image).merge(group_id: params[:group_id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:edit, :update]
  before_action :set_users, only: [:new, :edit]

  def index
    @groups = current_user.groups
  end


  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to group_messages_path(@group), notice: '成功しました'
    else
      flash.now[:alert] = '失敗しました'
      render :new
    end
  end

  def edit ; end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: '更新に成功しました'
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @users = User.except_for(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sub_column.html.haml
#sub
  .user
    .user__name
      = current_user.name
    .user__action
      .user__action--left
        = link_to edit_user_registration_path do
          .fa.fa-pencil-square-o
      .user__action--right
        = link_to new_group_path do
          .fa.fa-cog
  .groups
    - groups.each do |group|
      = link_to group_messages_path(group) do
        .group
          .group__name
            = group.name
          .group__message
            今日も晴天ですね〜〜〜。

app/views/groups/_form.html.haml
.chat-group-form
  %h1
    = title
  = form_for group, id: 'new_chat_group', class: 'new_chat_group' do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, id: 'chat_group_name', class: 'chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          -# %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-22.chat-group-user.clearfix
            %p.chat-group-user__name
              = f.hidden_field :user_ids, multiple: true, id: "group_users_ids_#{current_user.id}", value: current_user.id
              - if @users.present?
                = f.collection_check_boxes :user_ids, @users, :id, :name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
- title = 'チャットグループ編集'
= render 'groups/form', group: @group, title: title

app/views/groups/index.html.haml
= render 'application/sub_column', groups: @groups

app/views/groups/messages/_message.html.haml
.message
  .message__info
    .message__info--name
      = message.user.name
    .message__info--date
      = message.created_at
  .message__body
    = message.comment
  .message__image
    = image_tag message.image if message.image.present?

app/views/groups/messages/index.html.haml
= render 'application/sub_column', groups: @groups
#main
  .group
    .group__info
      .group__info--name
        = @group.name
      .group__info--member
        MEMBER:
        = @group.users.pluck(:name).join(', ')
    .group__edit
      = link_to edit_group_path(@group) do
        %span
          edit
  .messages
    = render @messages
  .input
    = form_for [@group, @message] do |f|
      .input__data
        = f.text_field :comment, placeholder: '文字を入れてください', class: 'input__data--text'
        .input__data--image
          = f.file_field :image
          .fa.fa-picture-o
      = f.submit "POST", class: 'input__post'

app/views/groups/new.html.haml
- title = '新規チャットグループ'
= render 'groups/form', group: @group, title: title

app/views/layouts/_devise_message.html.haml
- flash.each do |key, value|
  - key = "info" if key == "notice"
  - key = "danger"  if key == "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chatroom
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/devise_message'
    = yield

app/views/messages/index.html.haml
= render 'application/sub_column'
#main
  .group
    .group__info
      .group__info--name
        エンジニアグループ
      .group__info--member
        MEMBER:
        taketani, suzuki
    .group__edit
      = link_to edit_group_path(1) do
        %span
          edit
  .messages
    = render 'messages/message'
    = render 'messages/message'
  .input
    .input__data
      .input__data--text
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      .input__data--image
        .fa.fa-cog
    .input__post
      .input__post--submit
        POST